<a href="https://colab.research.google.com/github/bomij33/With-GANADA/blob/bomi/code/predict_model_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 모델 먼저 불러오기

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
# A, C 모델 로딩
from keras.models import load_model
model_A = load_model('/gdrive/MyDrive/Audio/model/ganada_A_220906.h5') 
model_C = load_model('/gdrive/MyDrive/Audio/model/ganada_C_220906.h5') 

# 앱에서 단계, 레이블, 녹음 파일(wav) 전달받으면
 - 레이블 index 결정
 - 단계에 해당하는 모델 사용

In [ ]:
test_label_0 = 0 # A 단계 label = 0 (아이) (전달받은 레이블 index)
test_label_1 = 1 # A 단계 1 (화가)
file_path = '/gdrive/MyDrive/Audio/test/10_test_data_30.wav' # 화가( 테스트용 wav) 전달받은 파일 path

import librosa
SAMPLING_RATE = 22050

test_x = []
test_data, _ = librosa.load(file_path, sr=SAMPLING_RATE)

test_x.append(test_data)

In [ ]:
# 테스트 코드 (들어보기용. 실제 실행시는 제거)
import IPython
print(test_label_1)
IPython.display.Audio(test_x[0], rate=SAMPLING_RATE)

1


In [ ]:
# padding
from tensorflow.keras.preprocessing import sequence

padded_test_x = sequence.pad_sequences(test_x, maxlen=22050, padding='post', dtype=float)
len(padded_test_x[0]) # 테스트용 코드

22050

In [ ]:
# numpy array로 변경
import numpy as np
test_x = np.array(padded_test_x)
print(test_x.shape)  # 테스트용 코드

(1, 22050)


In [ ]:
# 테스트 : 레이블 확인 및 소리 듣기 
print(test_label_1)
IPython.display.Audio(test_x[0], rate=SAMPLING_RATE)

1


In [ ]:
y_ = model_A.predict(test_x)

In [ ]:
y_  # 각 레이블별 정확도 확인

array([[2.9459827e-11, 1.0000000e+00, 1.5160958e-21]], dtype=float32)

In [ ]:
predicted = np.argmax(y_, axis=-1)

In [ ]:
# 정확도가 가장 높은 레이블의 정확도 확인
acc = y_[0]
acc[predicted[0]]  # 정확도

1.0

In [ ]:
# 모델 A로 '화가' 확인 : 100% 정확도

In [ ]:
# 정확도가 가장 높은 레이블의 id 확인
result_y = predicted[0]
result_y  # 레이블 ID 

1

# 부모 (C단계 0) 테스트

In [ ]:
test_label_c0 = 1 # C단계 0 부모

file_path_c0 = '/gdrive/MyDrive/Audio/test/09_test_data_26.wav' # 부모

import librosa
SAMPLING_RATE = 22050

test_x_c0 = []
test_data_c0, _ = librosa.load(file_path_c0, sr=SAMPLING_RATE)

test_x_c0.append(test_data_c0)

In [ ]:
# 테스트 코드 (들어보기용. 실제 실행시는 제거)
import IPython
print(test_label_c0)
IPython.display.Audio(test_x_c0[0], rate=SAMPLING_RATE)

# padding
from tensorflow.keras.preprocessing import sequence

padded_test_x_c0 = sequence.pad_sequences(test_x_c0, maxlen=22050, padding='post', dtype=float)
len(padded_test_x_c0[0]) # 테스트용 코드


1


22050

In [ ]:
# numpy array로 변경
import numpy as np
test_x_c0 = np.array(padded_test_x_c0)
print(test_x_c0.shape)  # 테스트용 코드

(1, 22050)


In [ ]:
# 테스트용 코드
print(test_label_c0)
IPython.display.Audio(test_x_c0[0], rate=SAMPLING_RATE)

1


In [ ]:
y_c0 = model_C.predict(test_x_c0)

In [ ]:
y_c0 # 각 레이블별 정확도 확인

array([[9.9365789e-01, 2.5881442e-05, 6.3162241e-03]], dtype=float32)

In [ ]:
predicted_c0 = np.argmax(y_c0, axis=-1)

In [ ]:
predicted_c0

array([0])

In [ ]:
# 정확도가 가장 높은 레이블의 정확도
acc = y_c0[0]
print("정확도 : ", acc[predicted_c0[0]])

# 정확도가 가장 높은 레이블의 id
print("레이블",predicted_c0[0] )


정확도 :  0.9936579
레이블 0


In [ ]:
# 모델 C로 '부모' 확인 : 99% 정확도